spring:
  datasource:
    url: jdbc:mariadb://localhost:3305/TarefasDataBase
    username: root
    password: lampi
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true